### ISSUE TITLE
"socket hung up" when deploying locally

### ISSUE THREAD

**Issue by danistefanovic** [graphcool/prisma#1028]
**Current behavior**
`gc deploy -t local` throws the following error:
```
 'ECONNRESET': request to http://localhost:60001/system failed, reason: socket hang up
```

**Reproduction**

```sh
❯❯❯ gc local up                                                                
Running local Graphcool cluster at http://localhost:60001
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   Pulling graphcool-db (mysql:5.7)...
docker   5.7: Pulling from library/mysql
docker   Digest: sha256:eb9a3bca059ee178b5a69a2443462d156ff5b3d3f739c516b62d9d902ba49132
docker   Status: Downloaded newer image for mysql:5.7
docker   Pulling localfaas (graphcool/localfaas:0.8.1)...
docker   0.8.1: Pulling from graphcool/localfaas
docker   Digest: sha256:7a1100b00a6928624af226da5c64ee97b4bd5a4991447e7e2865c2d9b17e5afa
docker   Status: Downloaded newer image for graphcool/localfaas:0.8.1
docker   Pulling graphcool-rabbit-host (rabbitmq:3-management)...
docker   3-management: Pulling from library/rabbitmq
docker   Digest: sha256:7c38808b3e7ca11e45aeda9a145a3ef9e6045c1d43f9c35f17a0918f688b3703
docker   Status: Downloaded newer image for rabbitmq:3-management
docker   Pulling graphcool (graphcool/graphcool-dev:0.8.1)...
docker   0.8.1: Pulling from graphcool/graphcool-dev
docker   Digest: sha256:27f6bc46868bf3b7f635ce23fa3f409d65aed0ede70e0a9f1c77fb5f400ec9e6
docker   Status: Downloaded newer image for graphcool/graphcool-dev:0.8.1
docker   Creating local_graphcool-db_1 ...
docker   Creating local_graphcool-rabbit-host_1 ...
docker   Creating local_localfaas_1 ...
docker   Creating local_localfaas_1
docker   Creating local_graphcool-rabbit-host_1
docker   Creating local_graphcool-db_1
Creating local_localfaas_1 ... done

docker   Creating local_graphcool-rabbit-host_1 ... done
docker   Creating local_graphcool_1 ...
Creating local_graphcool_1 ... done
docker

Waiting for Graphcool to initialize. This can take several minutes... ✔

Success! Cluster local already exists and is up-to-date.
To get started, execute

  $ graphcool init
  $ graphcool deploy

❯❯❯ gc deploy -t local                                                         
Bundling functions... 34.2s
Deploying to local with target local locally... !
 ▸    'ECONNRESET': request to http://localhost:60001/system failed, reason: socket hang up

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

When I open http://localhost:60001/system in the browser, the Graphcool Playground appears.

**Versions**
```
❯❯❯ gc --version
graphcool/0.8.1 (darwin-x64) node-v8.6.0

❯❯❯ docker --version
Docker version 17.09.0-ce, build afdb6d4

❯❯❯ docker images                                                            
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
graphcool/graphcool-dev   0.8.1               fd0a7d0c5755        46 hours ago        240MB
graphcool/localfaas       0.8.1               1cad1d584980        46 hours ago        176MB
mysql                     5.7                 5fac85ee2c68        8 days ago          408MB
rabbitmq                  3-management        2ac724eab066        11 days ago         124MB
```

**Comment by danistefanovic** [comment]
Here's are the last few lines from the output with `export DEBUG="*"`. I've removed some sensitive information. 

```
$ gc deploy --target local
...
bundler uploading to http://localhost:60051/functions/files/cj9v6xubl00170125tof73zro/cj9v7io6d009x012597z3qyvd +55s
  bundler {
  bundler   "success" : true
  bundler } +18s
  bundler bundled 84079 +0ms
 84.1s
  deploy bundled +1ms
Deploying to local with target local locally...  client
  client
  client Sending service definition: +18s
  client {
  client   "modules": [
  client     {
  client       "name": "",
  client       "content": "types: ./graphcool-types.graphql\nfunctions:\n  ...<truncated>",
  client       "files": {
  client         <truncated (some permission and function files) >
  client       },
  client       "externalFiles": {
  client         <truncated>
  client       }
  client     }
  client   ]
  client } +17ms
  client choosing clusterEndpoint http://localhost:60000/system +41ms
  client Sending query +0ms
  client       mutation($projectId: String!, $force: Boolean, $isDryRun: Boolean!, $config: String!) {
  client         push(input: {
  client           projectId: $projectId
  client           force: $force
  client           isDryRun: $isDryRun
  client           config: $config
  client           version: 1
  client         }) {
  client           migrationMessages {
  client             type
  client             action
  client             name
  client             description
  client             subDescriptions {
  client               type
  client               action
  client               name
  client               description
  client             }
  client           }
  client           errors {
  client             description
  client             type
  client             field
  client           }
  client           project {
  client             id
  client             name
  client             alias
  client             projectDefinitionWithFileContent
  client           }
  client         }
  client       }
  client      +0ms
  client { projectId: 'cj9v6xubl00170125tof73zro',
  client   force: undefined,
  client   isDryRun: false,
  client   config: '{"modules":[{"name":"","content":"types: ./graphcool-types.graphql\\nfunctions: ...<truncated>}]}' } +1ms
 !
FetchError: request to http://localhost:60000/system failed, reason: socket hang up
    at ClientRequest.<anonymous> (/Users/ds/.config/yarn/global/node_modules/cross-fetch/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketOnEnd (_http_client.js:437:9)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Exiting with code: 1
```

I've updated Graphcool CLI to 0.9.1 and Node to the newest LTS version but the error still appears. Any idea what this could be?

I'm currently in a place where the internet connectivity is not really great, to put it mildly. Without a working local development setup, I have to deploy every change to your servers which takes every time about 10 minutes (uploaded bundle is ~110MB) 🙈

**Comment by kbrandwijk** [comment]
It's a variation of https://github.com/graphcool/framework/issues/912.

Regarding your bundle size. Did you make sure to put your graphcool project in it's own folder (without any other things like a frontend client). The CLI takes the entire node_modules folder, and a large bundle size usually indicates that it's packaging things it doesn't need.

**Comment by danistefanovic** [comment]
That was my assumption that everything in the folder gets bundled. Was just to lazy to move the files around until now and I also didn't expect such a difference in the bundle size: 110MB => 4.3MB. One problem less 👍
