### ISSUE TITLE
`graphcool deploy` stops without error

### ISSUE THREAD

**Issue by schickling** [graphcool/prisma#1496]
![image](https://user-images.githubusercontent.com/1567498/34557519-cbd99442-f13a-11e7-839a-d74ae0615e1f.png)

Happens in the [server-example repo](https://github.com/graphcool/graphcool-server-example).

With `DEBUG '*'`

```
gc deploy
  config CWD /Users/schickling/Code/graphcool/os/workspace/packages/graphql-server-example +0ms
  config HOME /Users/schickling +2ms
  config definitionDir /Users/schickling/Code/graphcool/os/workspace/packages/graphql-server-example +0ms
  config definitionPath /Users/schickling/Code/graphcool/os/workspace/packages/graphql-server-example/graphcool.yml +0ms
  cli command id deploy +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/schickling/Library/Caches/graphcool/plugins.json +1ms
  cli:plugincache Got plugin from cache +2ms
  cli:plugincache /Users/schickling/Library/Caches/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +679ms
  plugin required command +682ms
  Environment migrating +0ms
  EnvironmentMigrator graphcoolPath /Users/schickling/.graphcool does not exist +0ms
  deploy run +0ms
  client choosing clusterEndpoint http://localhost:60000/cluster +0ms
  client Sending query +1ms
  client
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'example-airbnb', stage: 'dev' } +0ms
Deploying service `example-airbnb` to stage `dev` on cluster `local`...  client choosing clusterEndpoint http://localhost:60000/cluster +66ms
  client Sending query +0ms
  client       mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!]) {
  client         deploy(input: {
  client           name: $name
  client           stage: $stage
  client           types: $types
  client           dryRun: $dryRun
  client           secrets: $secrets
  client         }) {
  client           errors {
  client             type
  client             field
  client             description
  client           }
  client           migration {
  client             ...MigrationFragment
  client           }
  client         }
  client       }
  client
  client fragment MigrationFragment on Migration {
  client   revision
  client   steps {
  client     type
  client     __typename
  client     ... on CreateEnum {
  client       name
  client       ce_values: values
  client     }
  client     ... on CreateField {
  client       model
  client       name
  client       cf_typeName: typeName
  client       cf_isRequired: isRequired
  client       cf_isList: isList
  client       cf_isUnique: unique
  client       cf_relation: relation
  client       cf_defaultValue: default
  client       cf_enum: enum
  client     }
  client     ... on CreateModel {
  client       name
  client     }
  client     ... on CreateRelation {
  client       name
  client       leftModel
  client       rightModel
  client     }
  client     ... on DeleteEnum {
  client       name
  client     }
  client     ... on DeleteField {
  client       model
  client       name
  client     }
  client     ... on DeleteModel {
  client       name
  client     }
  client     ... on DeleteRelation {
  client       name
  client     }
  client     ... on UpdateEnum {
  client       name
  client       newName
  client       values
  client     }
  client     ... on UpdateField {
  client       model
  client       name
  client       newName
  client       typeName
  client       isRequired
  client       isList
  client       isUnique: unique
  client       relation
  client       default
  client       enum
  client     }
  client     ... on UpdateModel {
  client       name
  client       um_newName: newName
  client     }
  client   }
  client   hasBeenApplied
  client }
  client
  client      +0ms
  client { name: 'example-airbnb',
  client   stage: 'dev',
  client   types: 'type User {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  firstName: String!\n  lastName: String!\n  email: String! @unique\n  password: String!\n  phone: String!\n  responseRate: Float\n  responseTime: Int\n\n  isSuperHost: Boolean! @default(value: "false")\n  ownedPlaces: [Place!]!\n  location: Location\n  bookings: [Booking!]!\n  paymentAccount: [PaymentAccount!]!\n  sentMessages: [Message!]! @relation(name: "SentMessages")\n  receivedMessages: [Message!]! @relation(name: "ReceivedMessages")\n  notifications: [Notification!]!\n  profilePicture: Picture\n  hostingExperiences: [Experience!]!\n}\n\ntype Place {\n  id: ID! @unique\n  name: String\n  size: PLACE_SIZES\n  shortDescription: String!\n  description: String!\n  slug: String!\n  maxGuests: Int!\n  numBedrooms: Int!\n  numBeds: Int!\n  numBaths: Int!\n  reviews: [Review!]!\n  amenities: Amenities!\n  host: User!\n  pricing: Pricing!\n  location: Location!\n  views: Views!\n  guestRequirements: GuestRequirements\n  policies: Policies\n  houseRules: HouseRules\n  bookings: [Booking!]!\n  pictures: [Picture!]!\npopularity: Int!\n}\n\ntype Pricing {\n  id: ID! @unique\n  place: Place!\n  monthlyDiscount: Int\n  weeklyDiscount: Int\n  perNight: Int!\n  smartPricing: Boolean! @default(value: "false")\n  basePrice: Int!\n  averageWeekly: Int!\n  averageMonthly: Int!\n  cleaningFee: Int\n  securityDeposit: Int\n  extraGuests: Int\n  weekendPricing: Int\n  currency: CURRENCY\n}\n\ntype GuestRequirements {\n  id: ID! @unique\n  govIssuedId: Boolean! @default(value: "false")\n  recommendationsFromOtherHosts: Boolean! @default(value: "false")\n  guestTripInformation: Boolean! @default(value: "false")\n  place: Place!\n}\n\ntype Policies {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  checkInStartTime: Float!\n  checkInEndTime: Float!\n  checkoutTime: Float!\n  place: Place!\n}\n\ntype HouseRules {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  suitableForChildren: Boolean\n  suitableForInfants: Boolean\n  petsAllowed: Boolean\n  smokingAllowed: Boolean\n  partiesAndEventsAllowed: Boolean\n  additionalRules: String\n}\n\ntype Views {\n  id: ID! @unique\n  lastWeek: Int!\n  place: Place!\n}\n\ntype Location {\n  id: ID! @unique\n  lat: Float!\n  lng: Float!\n  neighbourHood: Neighbourhood\n  user: User\n  place: Place\n  address: String\n  directions: String\n  experience: Experience\n  restaurant: Restaurant\n}\n\ntype Neighbourhood {\n  id: ID! @unique\n  locations: [Location!]!\n  name: String!\n  slug: String!\n  homePreview: Picture\n  city: City!\n  featured: Boolean!\n  popularity: Int!\n}\n\ntype City {\n  id: ID! @unique\n  name: String!\n  neighbourhoods: [Neighbourhood!]!\n}\n\ntype Picture {\n  url: String!\n}\n\ntype Experience {\n  id: ID! @unique\n  category: ExperienceCategory\n  title: String!\n  host: User!\n  location: Location!\n  pricePerPerson: Int!\n  reviews: [Review!]!\n  preview: Picture!\n  popularity: Int!\n}\n\ntype ExperienceCategory {\n  id: ID! @unique\n  mainColor: String! @default(value: "#123456")\n  name: String!\n  experience: Experience\n}\n\ntype Amenities {\n  id: ID! @unique\n  place: Place!\n  elevator: Boolean! @default(value: "false")\n  petsAllowed: Boolean! @default(value: "false")\n  internet: Boolean! @default(value: "false")\n  kitchen: Boolean! @default(value: "false")\n  wirelessInternet: Boolean! @default(value: "false")\n  familyKidFriendly: Boolean! @default(value: "false")\n  freeParkingOnPremises: Boolean! @default(value: "false")\n  hotTub: Boolean! @default(value: "false")\n  pool: Boolean! @default(value: "false")\n  smokingAllowed: Boolean! @default(value: "false")\n  wheelchairAccessible: Boolean! @default(value: "false")\n  breakfast: Boolean! @default(value: "false")\n  cableTv: Boolean! @default(value: "false")\n  suitableForEvents: Boolean! @default(value: "false")\n  dryer: Boolean! @default(value: "false")\n  washer: Boolean! @default(value: "false")\n  indoorFireplace: Boolean! @default(value: "false")\n  tv: Boolean! @default(value: "false")\n  heating: Boolean! @default(value: "false")\n  hangers: Boolean! @default(value: "false")\n  iron: Boolean!@default(value: "false")\n  hairDryer: Boolean! @default(value: "false")\n  doorman: Boolean! @default(value: "false")\n  paidParkingOffPremises: Boolean! @default(value: "false")\n  freeParkingOnStreet: Boolean! @default(value: "false")\n  gym: Boolean! @default(value: "false")\n airConditioning: Boolean! @default(value: "false")\n  shampoo: Boolean! @default(value: "false")\n  essentials: Boolean! @default(value: "false")\n  laptopFriendlyWorkspace: Boolean! @default(value: "false")\n  privateEntrance: Boolean! @default(value: "false")\n  buzzerWirelessIntercom: Boolean! @default(value: "false")\n  babyBath: Boolean! @default(value: "false")\n  babyMonitor: Boolean! @default(value: "false")\n  babysitterRecommendations: Boolean! @default(value: "false")\n  bathtub: Boolean! @default(value: "false")\n  changingTable: Boolean! @default(value: "false")\n  childrensBooksAndToys: Boolean! @default(value: "false")\n  childrensDinnerware: Boolean! @default(value: "false")\n  crib: Boolean! @default(value: "false")\n}\n\ntype Review {\n  id: ID! @unique\n  createdAt: DateTime!\n  text: String!\n  stars: Int!\n  accuracy: Int!\n  location: Int!\n  checkIn: Int!\n  value: Int!\n  cleanliness: Int!\n  communication: Int!\n  place: Place!\n  experience: Experience\n}\n\ntype Booking {\n  id: ID! @unique\n  createdAt: DateTime!\n  bookee: User!\n  place: Place!\n  startDate: DateTime!\n  endDate:DateTime!\n  payment: Payment!\n}\n\ntype Payment {\n  id: ID! @unique\n  createdAt: DateTime!\n  serviceFee: Float!\n  placePrice: Float!\n  totalPrice: Float!\n  booking: Booking!\n  paymentMethod: PaymentAccount!\n}\n\ntype PaymentAccount {\n  id: ID! @unique\n  createdAt: DateTime!\n  type: PAYMENT_PROVIDER\n  user: User!\n  payments: [Payment!]!\n  paypal: PaypalInformation\n  creditcard: CreditCardInformation\n}\n\ntype PaypalInformation {\n  id: ID! @unique\n  createdAt: DateTime!\n  email: String!\n  paymentAccount: PaymentAccount!\n}\n\ntype CreditCardInformation {\n  id: ID! @unique\n  createdAt: DateTime!\n  cardNumber: String!\n  expiresOnMonth: Int!\n  expiresOnYear: Int!\n  securityCode: String!\n  firstName: String!\n  lastName: String!\n  postalCode: String!\n  country: String!\n  paymentAccount: PaymentAccount\n}\n\ntype Message {\n  id: ID! @unique\n  createdAt: DateTime!\n  from: User! @relation(name: "SentMessages")\n  to: User! @relation(name: "ReceivedMessages")\n  deliveredAt: DateTime!\n  readAt: DateTime!\n}\n\ntype Notification {\n  id: ID! @unique\n  createdAt: DateTime!\n  type: NOTIFICATION_TYPE\n  user: User!\n  link: String!\n  readDate: DateTime!\n}\n\ntype Restaurant {\n  id: ID! @unique\n  createdAt: DateTime!\n  title: String!\n  avgPricePerPerson: Int!\n  pictures: [Picture!]!\n  location: Location!\n  isCurated: Boolean! @default(value: "true")\n  slug: String!\n  popularity: Int!\n}\n\nenum CURRENCY {\n  CAD\n  CHF\n  EUR\n  JPY\n  USD\n  ZAR\n}\n\nenum PLACE_SIZES {\n  ENTIRE_HOUSE\n  ENTIRE_APARTMENT\n  ENTIRE_EARTH_HOUSE\n  ENTIRE_CABIN\n  ENTIRE_VILLA\n  ENTIRE_PLACE\n  ENTIRE_BOAT\n  PRIVATE_ROOM\n}\n\nenum PAYMENT_PROVIDER {\n  PAYPAL\n  CREDIT_CARD\n}\n\nenum NOTIFICATION_TYPE {\n  OFFER\n  INSTANT_BOOK\n  RESPONSIVENESS\n  NEW_AMENITIES\n  HOUSE_RULES\n}\n\n\n',
  client   dryRun: undefined,
  client   secrets: [ 'so-secret' ] } +1ms
 !
Error: You can not deploy to a service stage while there is a deployment in progress or a pending deployment scheduled already. Please try again after the deployment finished.: {"response":{"data":{"deploy":null},"errors":[{"locations":[{"line":2,"column":9}],"path":["deploy"],"code":4004,"message":"You can not deploy to a service stage while there is a deployment in progress or a pending deployment scheduled already. Please try again after the deployment finished.","requestId":"cluster:cluster:cjc0apjw500hl0131t421acpm"}],"status":200},"request":{"query":"     mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!]) {\n        deploy(input: {\n          name: $name\n          stage: $stage\n          types: $types\n          dryRun: $dryRun\n          secrets: $secrets\n        }) {\n          errors {\n            type\n            field\n            description\n          }\n          migration {\n            ...MigrationFragment\n          }\n        }\n      }\n      \nfragment MigrationFragment on Migration {\n  revision\n  steps {\n    type\n    __typename\n    ...on CreateEnum {\n      name\n      ce_values: values\n    }\n    ... on CreateField {\n      model\n      name\n      cf_typeName: typeName\n      cf_isRequired: isRequired\n      cf_isList: isList\n      cf_isUnique: unique\n      cf_relation: relation\n      cf_defaultValue: default\n      cf_enum: enum\n    }\n    ... on CreateModel {\n      name\n    }\n    ... on CreateRelation {\n      name\n      leftModel\n      rightModel\n    }\n    ... on DeleteEnum {\n      name\n    }\n    ... on DeleteField {\n      model\n      name\n    }\n    ... on DeleteModel {\n      name\n    }\n    ... on DeleteRelation {\n      name\n    }\n    ... on UpdateEnum {\n      name\n      newName\n      values\n    }\n    ... on UpdateField {\n      model\n      name\n      newName\n      typeName\n      isRequired\n      isList\n      isUnique: unique\n      relation\n      default\n      enum\n    }\n    ... on UpdateModel {\n      name\n      um_newName: newName\n    }\n  }\n  hasBeenApplied\n}\n\n    ","variables":{"name":"example-airbnb","stage":"dev","types":"type User {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  firstName: String!\n  lastName: String!\n  email: String! @unique\n  password: String!\n  phone: String!\n  responseRate: Float\n  responseTime: Int\n\n  isSuperHost: Boolean! @default(value: \"false\")\n  ownedPlaces: [Place!]!\n  location: Location\n  bookings: [Booking!]!\n  paymentAccount: [PaymentAccount!]!\n  sentMessages: [Message!]! @relation(name: \"SentMessages\")\n  receivedMessages: [Message!]! @relation(name: \"ReceivedMessages\")\n  notifications: [Notification!]!\n  profilePicture: Picture\n  hostingExperiences: [Experience!]!\n}\n\ntype Place {\n  id: ID! @unique\n  name: String\n  size: PLACE_SIZES\n  shortDescription: String!\n  description: String!\n  slug: String!\n  maxGuests: Int!\n  numBedrooms: Int!\n  numBeds: Int!\n  numBaths: Int!\n  reviews: [Review!]!\n  amenities: Amenities!\n  host: User!\n  pricing: Pricing!\n  location: Location!\n  views: Views!\n  guestRequirements: GuestRequirements\n  policies: Policies\n  houseRules: HouseRules\n  bookings: [Booking!]!\n  pictures: [Picture!]!\n  popularity: Int!\n}\n\ntype Pricing {\n  id: ID! @unique\n  place: Place!\n monthlyDiscount: Int\n  weeklyDiscount: Int\n  perNight: Int!\n  smartPricing: Boolean! @default(value: \"false\")\n  basePrice: Int!\n  averageWeekly: Int!\n  averageMonthly: Int!\n  cleaningFee: Int\n  securityDeposit: Int\n  extraGuests: Int\n  weekendPricing: Int\n  currency:CURRENCY\n}\n\ntype GuestRequirements {\n  id: ID! @unique\n  govIssuedId: Boolean! @default(value: \"false\")\n  recommendationsFromOtherHosts: Boolean! @default(value: \"false\")\n  guestTripInformation: Boolean! @default(value: \"false\")\n  place: Place!\n}\n\ntype Policies {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  checkInStartTime: Float!\n  checkInEndTime: Float!\n  checkoutTime: Float!\n  place: Place!\n}\n\ntype HouseRules {\n  id: ID! @unique\n  createdAt: DateTime!\n  updatedAt: DateTime!\n  suitableForChildren: Boolean\n  suitableForInfants: Boolean\n  petsAllowed: Boolean\n  smokingAllowed: Boolean\n  partiesAndEventsAllowed: Boolean\n  additionalRules: String\n}\n\ntype Views {\n  id: ID! @unique\n  lastWeek: Int!\n  place: Place!\n}\n\ntype Location {\n  id: ID! @unique\n  lat: Float!\n  lng: Float!\n  neighbourHood: Neighbourhood\n  user: User\n  place: Place\n  address: String\n  directions: String\n  experience: Experience\n  restaurant: Restaurant\n}\n\ntype Neighbourhood {\n  id: ID! @unique\n  locations: [Location!]!\n  name: String!\n  slug: String!\n  homePreview: Picture\n  city: City!\n  featured: Boolean!\n  popularity: Int!\n}\n\ntype City {\n  id: ID! @unique\n  name: String!\n  neighbourhoods: [Neighbourhood!]!\n}\n\ntype Picture {\n  url: String!\n}\n\ntype Experience {\n  id: ID! @unique\n  category: ExperienceCategory\n  title: String!\n  host: User!\n  location: Location!\n  pricePerPerson: Int!\n  reviews: [Review!]!\n  preview: Picture!\n  popularity: Int!\n}\n\ntype ExperienceCategory {\n  id: ID! @unique\n  mainColor: String! @default(value: \"#123456\")\n  name: String!\n  experience: Experience\n}\n\ntype Amenities {\n  id: ID! @unique\n  place: Place!\n  elevator: Boolean! @default(value: \"false\")\n  petsAllowed: Boolean! @default(value: \"false\")\n  internet: Boolean! @default(value: \"false\")\n  kitchen: Boolean! @default(value: \"false\")\n  wirelessInternet: Boolean! @default(value: \"false\")\n  familyKidFriendly: Boolean! @default(value: \"false\")\n  freeParkingOnPremises: Boolean! @default(value: \"false\")\n  hotTub: Boolean! @default(value: \"false\")\n  pool: Boolean! @default(value: \"false\")\n  smokingAllowed: Boolean! @default(value: \"false\")\n  wheelchairAccessible: Boolean! @default(value: \"false\")\n  breakfast: Boolean! @default(value: \"false\")\n  cableTv: Boolean! @default(value: \"false\")\n  suitableForEvents: Boolean! @default(value: \"false\")\n  dryer: Boolean! @default(value: \"false\")\n  washer: Boolean! @default(value: \"false\")\n  indoorFireplace: Boolean! @default(value: \"false\")\n  tv: Boolean! @default(value: \"false\")\n  heating: Boolean! @default(value: \"false\")\n  hangers: Boolean! @default(value: \"false\")\n  iron: Boolean! @default(value: \"false\")\n  hairDryer: Boolean! @default(value: \"false\")\n  doorman: Boolean! @default(value: \"false\")\n  paidParkingOffPremises: Boolean! @default(value: \"false\")\n  freeParkingOnStreet: Boolean! @default(value: \"false\")\n  gym: Boolean! @default(value: \"false\")\n  airConditioning: Boolean! @default(value: \"false\")\n  shampoo: Boolean! @default(value: \"false\")\n  essentials: Boolean! @default(value: \"false\")\n  laptopFriendlyWorkspace: Boolean! @default(value: \"false\")\n  privateEntrance: Boolean! @default(value: \"false\")\n  buzzerWirelessIntercom: Boolean! @default(value: \"false\")\n  babyBath: Boolean! @default(value: \"false\")\n  babyMonitor: Boolean! @default(value: \"false\")\n  babysitterRecommendations: Boolean! @default(value: \"false\")\n  bathtub: Boolean! @default(value: \"false\")\n  changingTable: Boolean!@default(value: \"false\")\n  childrensBooksAndToys: Boolean! @default(value: \"false\")\n  childrensDinnerware: Boolean! @default(value: \"false\")\n  crib: Boolean! @default(value: \"false\")\n}\n\ntype Review {\n  id: ID! @unique\n  createdAt: DateTime!\n  text: String!\n  stars: Int!\n  accuracy: Int!\n  location: Int!\n  checkIn: Int!\n  value: Int!\n  cleanliness: Int!\n  communication: Int!\n  place: Place!\n  experience: Experience\n}\n\ntype Booking {\n  id: ID! @unique\n  createdAt: DateTime!\n  bookee: User!\n  place: Place!\n  startDate: DateTime!\n  endDate: DateTime!\n  payment: Payment!\n}\n\ntype Payment {\n  id: ID! @unique\n  createdAt: DateTime!\n  serviceFee: Float!\n  placePrice: Float!\n  totalPrice: Float!\n  booking: Booking!\n  paymentMethod: PaymentAccount!\n}\n\ntype PaymentAccount {\n  id: ID! @unique\n  createdAt: DateTime!\n  type: PAYMENT_PROVIDER\n  user: User!\n  payments: [Payment!]!\n  paypal: PaypalInformation\n  creditcard: CreditCardInformation\n}\n\ntype PaypalInformation {\n  id: ID! @unique\n  createdAt: DateTime!\n  email: String!\n  paymentAccount: PaymentAccount!\n}\n\ntype CreditCardInformation {\n  id: ID! @unique\n  createdAt: DateTime!\n  cardNumber: String!\n  expiresOnMonth: Int!\n  expiresOnYear: Int!\n  securityCode: String!\n  firstName: String!\n  lastName: String!\n  postalCode: String!\n  country: String!\n  paymentAccount: PaymentAccount\n}\n\ntype Message {\n  id: ID! @unique\n  createdAt: DateTime!\n  from: User! @relation(name: \"SentMessages\")\n  to: User! @relation(name: \"ReceivedMessages\")\n  deliveredAt: DateTime!\n  readAt: DateTime!\n}\n\ntype Notification {\n  id: ID! @unique\n  createdAt: DateTime!\n  type: NOTIFICATION_TYPE\n  user: User!\n  link: String!\n  readDate: DateTime!\n}\n\ntype Restaurant {\n  id: ID! @unique\n  createdAt: DateTime!\n  title: String!\n  avgPricePerPerson: Int!\n  pictures: [Picture!]!\n  location: Location!\n  isCurated: Boolean! @default(value: \"true\")\n  slug: String!\n  popularity: Int!\n}\n\nenum CURRENCY {\n  CAD\n  CHF\n  EUR\n  JPY\n  USD\n  ZAR\n}\n\nenum PLACE_SIZES {\n  ENTIRE_HOUSE\n  ENTIRE_APARTMENT\n  ENTIRE_EARTH_HOUSE\n  ENTIRE_CABIN\n  ENTIRE_VILLA\n  ENTIRE_PLACE\n  ENTIRE_BOAT\n  PRIVATE_ROOM\n}\n\nenum PAYMENT_PROVIDER {\n  PAYPAL\n  CREDIT_CARD\n}\n\nenum NOTIFICATION_TYPE {\n  OFFER\n  INSTANT_BOOK\n  RESPONSIVENESS\n  NEW_AMENITIES\n  HOUSE_RULES\n}\n\n\n","secrets":["so-secret"]}}}
    at GraphQLClient.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/src/index.ts:46:13)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/usr/local/lib/node_modules/graphcool/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```
 
- [x] General: handle errors gracefully
- [x] Better error handling for special case: deploy in progress

**Comment by timsuchanek** [comment]
Fixed in 1.0
