### ISSUE TITLE
prisma cluster logs silently exits or stops docker container

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1599]
Version: `graphcool/1.0.0-alpha4.2.3`

`gc cluster logs` for local cluster either
- forces me to stop local docker
- or prints nothing and exits after a couple of seconds

Reproduction:

```
graphcool init my-app --boilerplate typescript-advanced
# choose local cluster
cd my-app
graphcool cluster logs
```

You'll be prompted to stop the docker container:

![image](https://user-images.githubusercontent.com/1780597/34892892-3ffbba52-f7db-11e7-9b53-c5c7b88f34dc.png)

If you then stop it and run `graphcool cluster logs` again, this is the output:

![image](https://user-images.githubusercontent.com/1780597/34892935-5ff0b1a0-f7db-11e7-8f8e-4e41da42e68d.png)

Debug logs are:

```
  portfinder:getPort in eachSeries() result callback: err is { Error: listen EADDRNOTAVAIL fe80::1:60000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1504:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

---

  Docker Attaching to
  Docker  +2s
  cli not flushing +3s
```

**Comment by marktani** [comment]
Was fixed a while ago 🎉
