### ISSUE TITLE
prisma list: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1600]
Version: `graphcool/1.0.0-alpha4.2.3`

reproduction:

```sh
graphcool init my-app -b typescript-advanced
# deploy to local
graphcool list
```

stacktrace:

```
TypeError: Cannot read property 'name' of null
    at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/list/index.ts:46:25
    at Array.map (<anonymous>)
    at List.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/list/index.ts:43:37)
    at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/list/index.js:50:23)
    at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/list/index.js:31:53)
    at fulfilled (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/list/index.js:22:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by timsuchanek** [comment]
Fixed in latest version
