### ISSUE TITLE
No field except "id" can contain the substring "id"

### ISSUE THREAD

**Issue by KATT** [graphcool/prisma#1733]
## Current behavior

When we have any field named anything containing `id` - lowercased or uppercased or whatever, that field is not requested from remote GraphQL server

## Reproduction

1. clone https://github.com/KATT/whycantihaveidinmyname
2. `yarn dev`
3. run following query:
```graphql
{
  feed {
    title
    text

    id
    rewardId
    canMyIdBeReceived
    myId
    uuid
  }
}
```

### Expected behavior

Returns posts and fields

### Actual 

Errors

```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Post.rewardId.",
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "feed",
        0,
        "rewardId"
      ]
    }
  ]
}
```

The propagated GraphQL query omits `id`. It only queries for `title` `text` `id`

From terminal:

```sh
Request to https://eu1.prisma.sh/public-brownglass-244/whycantihaveidinmyname/dev:
query:
query ($_where: PostWhereInput, $_orderBy: PostOrderByInput, $_skip: Int, $_after: String, $_before: String, $_first: Int, $_last: Int) {
  posts(where: $_where, orderBy: $_orderBy, skip: $_skip, after: $_after, before: $_before, first: $_first, last: $_last) {
    title
    text
    id
  }
}
operationName: null
variables:
{
  "_where": {
    "isPublished": true
  }
}
Response from https://eu1.prisma.sh/public-brownglass-244/whycantihaveidinmyname/dev:
{
  "posts": [
    {
      "title": "Hello World",
      "text": "This is my first blog post ever!",
      "id": "cjcune9q3l0ar0189aurgnosc"
    },
    {
      "title": "My Second Post",
      "text": "My first post was good, but this one is better!",
      "id": "cjcune9q3l0as018987xlhcp6"
    }
  ]
}
Error: Cannot return null for non-nullable field Post.rewardId.
    at completeValue (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:648:13)
    at completeValueWithLocatedError (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:595:21)
    at completeValueCatchingError (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:564:12)
    at resolveField (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:510:10)
    at ~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:357:18
    at Array.reduce (<anonymous>)
    at executeFields (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:354:42)
    at collectAndExecuteSubfields (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:799:10)
    at completeObjectValue (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:781:10)
    at completeValue (~/dev/whycantihaveidinmyname/node_modules/graphql/execution/execute.js:677:12)
```

**Comment by KATT** [comment]
@marktani @schickling 
Can I get some pointers on where I could start digging? It seems to be something in binding. I had a quick look and I couldn't see any easy-to-find test where I could get it to fail and start hacking away.

**Comment by KATT** [comment]
Seem to have been that the TS definition wasn't regenerated and that `yarn graphql prepare` solves it! 🎉

**Comment by marktani** [comment]
Thanks a lot for the digging, @KATT! This is also covered here, for anyone interested: https://github.com/graphcool/prisma/issues/1695.
