### ISSUE TITLE
trouble creating account in prisma cloud w/ github auth

### ISSUE THREAD

**Issue by brandonmp** [graphcool/prisma#1736]
On Win10, latest version of prisma. chrome latest, adblocker disabled. 

**Current behavior**
in powershell, I type `prisma login`
This loads the login window. At that point, the chrome console throws the following:

```
ObservableQuery.js:289 Unhandled error GraphQL error: Not authorized. Please provide a proper 'Authorization' header Error: GraphQL error: Not authorized. Please provide a proper 'Authorization' header
    at new t (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:103120)
    at https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:592370
    at https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:599293
    at Array.forEach (<anonymous>)
    at https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:599273
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:599180)
    at Object.next (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:600000)
    at p.next (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:578914)
    at https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:602544
e._subscription.e._subscription._observer.e._subscription._observer.error.e._subscription._observer.error @ ObservableQuery.js:289
2react-apollo.browser.umd.js:545 Unhandled (in react-apollo:Apollo(withRouter(t))) Error: GraphQL error: Not authorized. Please provide a proper 'Authorization' header
    at new t (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:103120)
    at t.currentResult (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:93940)
    at l.dataForChild (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:43848)
    at l.render (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:44694)
    at s (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:270374)
    at beginWork (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:272094)
    at o (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:284219)
    at a (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:284540)
    at u (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:284778)
    at _ (https://app.prismagraphql.com/static/js/main.bbcec6ea.js:1:288322)
```

Then, I try to login with Github. Authorizing graphcool in Github works fine, but then on redirect the console throws:
```
2api.cloud.prisma.sh/:1 POST https://api.cloud.prisma.sh/ 400 ()
github:1 

Failed to load https://api.cloud.prisma.sh/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://app.prismagraphql.com' is therefore not allowed access. The response had HTTP status code 400. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Clicking 'submit' on the confirmation screen then triggers a toast that says "Failed to fetch:
![image](https://user-images.githubusercontent.com/14139991/35424234-3a28a7ee-0220-11e8-8c04-6523581f1a5c.png)

Going directly to `app.prismagraphql.com` and registering w/ email/password works as expected.

**Comment by timsuchanek** [comment]
Thanks for reporting @brandonmp. This should be fixed by now. Please reopen if still an issue.

**Comment by sedubois** [comment]
I naively went to app.prismagraphql.com, said that I already have an account, put my Graphcool credentials (in case they are shared with Graph.cool, don't know), and got this error when trying to grant permissions:

<img width="836" alt="screen shot 2018-01-29 at 12 32 48" src="https://user-images.githubusercontent.com/4217871/35506024-a9822f20-04f0-11e8-9856-cceebab150c2.png">

**Comment by kjetilge** [comment]
I'm havning problem signing up. Get this error message:
```
GraphQL error: Variable '$_data' expected value of type 'UserCreateInput!' but got: {"name":"Kjetil Geirbo","login":{"create":[{"email":"xxxx@xxxxx.com","isEmailVerified":false,"emailVerificationCode":"$2a$08$stgzkw/et32g.RKJ5/OUqu","passwordHash":"$xxxxx"}]},"memberships":{"create":[{"workspace":{"create":{"name":"Kjetil Geirbo","slug":"kjetil-geirbo","clusters":{"create":[{"isDeleted":false,"name":"prisma-eu1"},{"isDeleted":false,"name":"prisma-us1"}]}}}}]}}. Reason: 'memberships.create[0].workspace.create.clusters.create[0].isDeleted' Field 'isDeleted' is not defined in the input type 'ClusterCreateWithoutWorkspaceInput'. (line 1, column 11): mutation ($_data: UserCreateInput!) { ^
```
