### ISSUE TITLE
using "connect" in mutations fails after upgrading prisma to 1.0.10

### ISSUE THREAD

**Issue by rohitghatol** [graphcool/prisma#1754]
# Summary
It is my observation that using "connect" in mutations have started to fail after
1. Upgrading prisma to 1.0.10
2. Upgrading Docker Image - `$>prisma local upgrade`

I can not say for sure what causes this, as I did both at once

## Environment - 
1. Local Cluster
2. Prisma Version - 1.0.10 
```
$>prisma -v
prisma/1.0.10 (darwin-x64) node-v8.7.0
```
3. Prisma Docker Version - 1.0 
```
$>docker images
REPOSITORY                                         TAG                            IMAGE ID            CREATED             SIZE
prismagraphql/prisma                               1.0                            8ccb39ee60ce        9 hours ago         198MB

$>docker ps 
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS              PORTS                    NAMES
5c27af6c9546        prismagraphql/prisma:1.0   "/app/bin/single-ser…"   About a minute ago   Up About a minute   0.0.0.0:4466->4466/tcp   local_prisma-database_1
87d02d4db7bc        mysql:5.7                  "docker-entrypoint.s…"   3 minutes ago        Up 3 minutes        0.0.0.0:3307->3306/tcp   prisma-db


```

## Schema - 
```

type Role {

  id: ID! @unique

  name: String! @unique

}

type User {

  id: ID! @unique

  name: String!

  roles:[Role!]!

}

```

## Mutations -

```
mutation{
  deleteManyUsers(where:{}){
    count
  }
  deleteManyRoles(where:{}){
    count
  }
  Role1:createRole(
        data:{
            name:"Role1"
        }
    ){
        id
        name
    }
    Role2:createRole(
        data:{
            name:"Role2"
        }
    ){
        id
        name
    }

   User1WithRole1: createUser(
        data:{
            name:"User1",
            roles:{
                connect:{
                    name:"Role1"
                }
            }
        }
    ){
        id
        name
        roles {
            name
        }
    }
   User2WithRole1Role2: createUser(
        data:{
            name:"User2",
            roles:{
                connect:[
                  {
                    name:"Role1"
                  },
                  {
                    name:"Role2"
                  }
                ]
            }
        }
    ){
        id
        name
        roles {
            name
        }
    }
}
```

## Observations - 
1. The Mutation User1WithRole1 and User2WithRole1Role2 used to work before the upgrade of Prisma and Prisma Docker Images
2. The Mutation User1WithRole1 and User2WithRole1Role2 give following error after upgrade of Prisma and Prisma docker image

```
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjcy88xxb000i01722waaieju",
      "path": [
        "User1WithRole1"
      ],
      "locations": [
        {
          "line": 25,
          "column": 4
        }
      ],
      "requestId": "api:api:cjcy88xxb000i01722waaieju"
    }
  ]
}
```

## Additional Information - 

Docker Logs show the following Error - 

```
Listening for transport dt_socket at address: 8000
Obtaining exclusive agent lock...
Obtaining exclusive agent lock... Successful.
Deployment worker initialization complete.
Initializing workers...
Successfully started 1 workers.
Server running on :4466
{"@timestamp":"2018-01-28T03:28:11.911+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86esi000001726s9z0vkt\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-19","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
[Metrics] Warning: no metrics will be recorded.
Version is up to date.
{"@timestamp":"2018-01-28T03:28:13.355+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86esi000001726s9z0vkt\",\"payload\":\"Map(request_duration -> 1480)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-2","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:14.111+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86gim00010172i9cg5qi2\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-5","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:14.128+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86gim00010172i9cg5qi2\",\"payload\":\"Map(request_duration -> 17)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-19","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:14.152+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86gjs00020172q6remcta\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-5","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:14.896+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86gjs00020172q6remcta\",\"payload\":\"Map(request_duration -> 744)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-2","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:14.915+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86h4z00030172ack631a5\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-2","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:15.386+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86h4z00030172ack631a5\",\"payload\":\"Map(request_duration -> 471)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-2","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:15.409+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86hip00040172yvt61oyh\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-21","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
[Debug] Initializing deployment worker for tmp@dev
[Debug] Scheduling deployment for project tmp@dev
{"@timestamp":"2018-01-28T03:28:15.962+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86hip00040172yvt61oyh\",\"payload\":\"Map(request_duration -> 552)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-5","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:15.984+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86hyn000701727hun821y\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-5","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:16.044+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86hyn000701727hun821y\",\"payload\":\"Map(request_duration -> 61)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-5","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
[Debug] Applied migration for project tmp@dev
{"@timestamp":"2018-01-28T03:28:16.565+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"cluster:cluster:cjcy86iet000801728s0vw55v\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-21","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:16.614+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"cluster:cluster:cjcy86iet000801728s0vw55v\",\"payload\":\"Map(request_duration -> 49)\"}","logger_name":"com.prisma.deploy.server.ClusterServer","thread_name":"single-server-akka.actor.default-dispatcher-19","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
{"@timestamp":"2018-01-28T03:28:17.140+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjcy86iur00090172ppc3gua0\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-21","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
[Metrics] Warning: no metrics will be recorded.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
PUBLISHING SUBSCRIPTION EVENT TO Only(subscription:event:tmp@dev:createRole)
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
PUBLISHING SUBSCRIPTION EVENT TO Only(subscription:event:tmp@dev:createRole)
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at com.prisma.api.database.mutactions.mutactions.NestedConnectRelationMutaction.execute(NestedConnectRelationMutaction.scala:19)
        at com.prisma.api.database.mutactions.TransactionMutaction.$anonfun$execute$1(TransactionMutaction.scala:15)
        at scala.collection.immutable.List.map(List.scala:287)
        at com.prisma.api.database.mutactions.TransactionMutaction.execute(TransactionMutaction.scala:15)
        at com.prisma.api.mutations.ClientMutationRunner$.runWithErrorHandler(ClientMutationRunner.scala:86)
        at com.prisma.api.mutations.ClientMutationRunner$.runWithTiming(ClientMutationRunner.scala:78)
        at com.prisma.api.mutations.ClientMutationRunner$.$anonfun$performGroup$3(ClientMutationRunner.scala:65)
        at com.prisma.utils.future.FutureUtils$DeferredFutureCollectionExtensions$.$anonfun$runSequentially$2(FutureUtils.scala:37)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@45f44548
{"@timestamp":"2018-01-28T03:30:09.983+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjcy88xxb000i01722waaieju\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-15","level":"INFO","level_value":20000,"HOSTNAME":"ec415969c4cf"}
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
PUBLISHING SUBSCRIPTION EVENT TO Only(subscription:event:tmp@dev:createRole)
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
PUBLISHING SUBSCRIPTION EVENT TO Only(subscription:event:tmp@dev:createRole)
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
[Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at com.prisma.api.database.mutactions.mutactions.NestedConnectRelationMutaction.execute(NestedConnectRelationMutaction.scala:19)
        at com.prisma.api.database.mutactions.TransactionMutaction.$anonfun$execute$1(TransactionMutaction.scala:15)
        at scala.collection.immutable.List.map(List.scala:287)
        at com.prisma.api.database.mutactions.TransactionMutaction.execute(TransactionMutaction.scala:15)
        at com.prisma.api.mutations.ClientMutationRunner$.runWithErrorHandler(ClientMutationRunner.scala:86)
        at com.prisma.api.mutations.ClientMutationRunner$.runWithTiming(ClientMutationRunner.scala:78)
        at com.prisma.api.mutations.ClientMutationRunner$.$anonfun$performGroup$3(ClientMutationRunner.scala:65)
        at com.prisma.utils.future.FutureUtils$DeferredFutureCollectionExtensions$.$anonfun$runSequentially$2(FutureUtils.scala:37)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@c88712e


```

**Comment by sorenbs** [comment]
@do4gr has been working on this area of the code lately and should be able to figure out what is going on

**Comment by do4gr** [comment]
Thanks for reporting this @rohitghatol. I had a look and it is caused by the new optional backrelation fields. I will adjust the checks to not always assume there are two relationfields in the next days. As a quick fix you should be able to define the backrelationfield on role as an immediate workaround @rohitghatol. Sorry for the inconvenience.
