### ISSUE TITLE
error pointing to logs, but logs are empty

### ISSUE THREAD

**Issue by brandonmp** [graphcool/prisma#1758]
Windows 10 in powershell
prisma 1.0.11

```
[GraphQL error]: Message: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjcz0ihup0zq70112qnlxiikq, Location: [object Object], Path: createUser
Response from https://us1.prisma.sh/brandon/optics-prisma/dev:
null
Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjcz0ihup0zq70112qnlxiikq
    at Object.checkResultAndHandleErrors (C:\Users\brand\code\optics-prisma\node_modules\graphql-tools\src\stitching\errors.ts:84:7)
    at Object.<anonymous> (C:\Users\brand\code\optics-prisma\node_modules\graphql-tools\src\stitching\delegateToSchema.ts:97:14)
    at step (C:\Users\brand\code\optics-prisma\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:40:23)
    at Object.next (C:\Users\brand\code\optics-prisma\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:21:53)
    at fulfilled (C:\Users\brand\code\optics-prisma\node_modules\graphql-tools\dist\stitching\delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
^CTerminate batch job (Y/N)? y

PS C:\Users\brand\code\optics-prisma> prisma local logs

PS C:\Users\brand\code\optics-prisma>
```

Unsure how to repro b/c I'm not sure what's causing the error, but here's the type I"m trying to create: 

```
type User {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    linkedInUserId: String! @unique
    email: String! @unique
    linkedInProfile: Json
    firstName: String
    lastName: String
    linkedInIndustry: String
    linkedInPublicProfileUrl: String
    linkedInLocation: String
    linkedInPhotoUrl: String
    linkedInJobTitle: String
    linkedInEmployerName: String
    linkedInEmployerId: String
}

```

And here's the payload being passed:

```
{
  "data": {
    "linkedInUserId": "etc",
    "email": "etc",
    "linkedInProfile": "some big long json string",
    "firstName": "Brandon",
    "lastName": "lastname",
    "linkedInIndustry": "etc",
    "linkedInPublicProfileUrl": "etc",
    "linkedInLocation": "etc",
    "linkedInPhotoUrl": "etc"
  }
}
```

Note that I"m passing a string to a Json field b/c I'm not sure if it's string or object, but passing an object yields the same error, so I don't think that's a part of the issue.

ETA: messing around in gql playground & it appears removing the Json field lets the `createUser` happen, but still returns an error in the `errors` prop:

```
mutation {
  createUser(data: { 
       email: "blahblashz", 
       firstName: "etc", 
       lastName: "etc", 
       linkedInUserId: "potsatso"
}) {
    email
    firstName
    lastName
    linkedInUserId
  }
}


// begets
{
  "data": {
    "createUser": {
      "email": "blahblashz",
      "linkedInEmployerName": null,
      "linkedInLocation": null,
      "lastName": "etc",
      "firstName": "etc",
      "linkedInProfile": null,
      "linkedInUserId": "potsatso",
      "linkedInPhotoUrl": null,
      "linkedInIndustry": null,
      "linkedInJobTitle": null,
      "linkedInEmployerId": null,
      "linkedInPublicProfileUrl": null
    }
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjcz171uy15wf011258qcglhr",
      "path": [
        "createUser",
        "linkedInProfile"
      ],
      "locations": [
        {
          "line": 20,
          "column": 1
        }
      ],
      "requestId": "api:api:cjcz171uy15wf011258qcglhr"
    }
  ]
}
```

**Comment by marktani** [comment]
Are you using `prisma cluster logs`?

**Comment by marktani** [comment]
I'm closing this due to inactivity. Please open a new issue if you still encounter any problems :slightly_smiling_face:
