### ISSUE TITLE
Upsert fails with parameters out of order

### ISSUE THREAD

**Issue by a-type** [graphcool/prisma#1761]
After writing an upsert mutation, I was surprised to see a 500 from the Prisma server. Looking in the Docker logs, it seems like the parameters for the SQL query are not relayed in order. Specifically, the `type` variable is being assigned to the `id` field in the database, which triggers a uniqueness constraint error.

It appears that `type` is getting pushed to the end of the SELECT clause parameters, even though it's listed as the 4th parameter in the INSERT clause. Could it be related to type being a custom enum, or maybe even its position in the original schema definition?

Type definition:

```
type Permission {
  id: ID! @unique
  name: String! @unique
  crudKey: String! @unique
  type: PermissionType!

  resourceName: String
  allowedOperation: CrudOperation

  customOperation: CustomOperation @relation(name: "CustomOperationOnPermission")

  users: [User!]! @relation(name: "UserOnPermissions")
  groups: [PermissionGroup!]! @relation(name: "PermissionGroupOnPermissions")
}
```

Query:

```js
const permission = {
  resourceName: 'Node',
  allowedOperation: 'UPDATE',
  key: 'Node:UPDATE'
};

context.db.mutation.upsertPermission({ 
  create: {
    name: permission.key,
    crudKey: permission.key,
    type: 'CRUD',
    resourceName: permission.resourceName,
    allowedOperation: permission.allowedOperation,
  },
  update: {
    resourceName: permission.resourceName,
    allowedOperation: permission.allowedOperation,
  },    
  where: {     
    crudKey: permission.key,
  },
})
```

Error in Docker logs:

```
[Bugsnag - local / testing] Error report: com.bugsnag.Report@32174158
Caused by: java.sql.SQLException: Duplicate entry 'CRUD' for key 'PRIMARY'
Query is: INSERT INTO `prisma-admin@dev`.`Permission` ( `name` , `allowedOperation` , `crudKey` , `type` , `resourceName` , `id` ) SELECT  ? , ? , ? , ? , ? , ? FROM DUAL where not exists (
select `id` from `prisma-admin@dev`.`Permission` where `crudKey` = ? limit 1);, parameters ['Node:UPDATE','UPDATE','Node:UPDATE','Node','cjcznwwpu00ce01675iv1ijqf','CRUD','Node:UPDATE']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 24 more
java.sql.SQLIntegrityConstraintViolationException: (conn=37) Duplicate entry 'CRUD' for key 'PRIMARY'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:157)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
        at slick.jdbc.Invoker.first(Invoker.scala:31)
        at slick.jdbc.Invoker.first$(Invoker.scala:30)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@66ca7960
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[Bugsnag - local / testing] Error report: com.bugsnag.Report@3aa0309c
Caused by: java.sql.SQLException: Duplicate entry 'CRUD' for key 'PRIMARY'
Query is: INSERT INTO `prisma-admin@dev`.`Permission` ( `name` , `allowedOperation` , `crudKey` , `type` , `resourceName` , `id` ) SELECT  ? , ? , ? , ? , ? , ? FROM DUAL where not exists (
select `id` from `prisma-admin@dev`.`Permission` where `crudKey` = ? limit 1);, parameters ['Node:DELETE','DELETE','Node:DELETE','Node','cjcznwwro00cn0167tc089duu','CRUD','Node:DELETE']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 24 more
```

**Comment by marktani** [comment]
What's your `prisma version` and version of the local cluster `prisma cluster list`?

**Comment by a-type** [comment]
I made sure to run `prisma deploy` with `1.0.11` before posting, but I'll double check it when I'm back home this evening.

**Comment by seanchambo** [comment]
I am having this same issue @marktani! Also running version 1.0.11 on the cluster.

**Comment by seanchambo** [comment]
Not sure but it looks like something to do with these lines and the result `raw.keys` and `raw.values` returning in different orders potentially.

```java
 val escapedColumns = combineByComma(createArgs.raw.keys.map(escapeKey))
 val insertValues   = combineByComma(createArgs.raw.values.map(escapeUnsafeParam))
 (sql"INSERT INTO `#${projectId}`.`#${where.model.name}` (" ++ escapedColumns ++ sql")" ++
   sql"SELECT " ++ insertValues ++
   sql"FROM DUAL" ++
   sql"where not exists (select `id` from `#${projectId}`.`#${where.model.name}` where `#${where.field.name}` = ${where.fieldValue} limit 1);").asUpdate
```

**Comment by seanchambo** [comment]
Doing something like this is much more safe:

```java
val escapedKeyValueTuples = args.raw.toList.map(x => (escapeKey(x._1), escapeUnsafeParam(x._2)))
val escapedKeys           = combineByComma(escapedKeyValueTuples.map(_._1))
val escapedValues        = combineByComma(escapedKeyValueTuples.map(_._2))
```

**Comment by ivanhodos** [comment]
hi Guys
looks like the issue still produced

prisma -v
`prisma/1.1.3 (windows-x64) node-v9.3.0`

prisma cluster list
```
name        version  endpoint
──────────  ───────  ─────────────────────────────
local       1.1.3    http://localhost:4466/cluster
prisma-eu1  1.1.0    https://eu1.prisma.sh/cluster
prisma-us1  1.1.0    https://us1.prisma.sh/cluster
```

Type definition:
```
type TestData {
  id: ID! @unique
  testId: Int! @unique
  testNumber: String
  testAmount: Int
  testCurrency: Int
  testStatus: String
}
```
Query:
```
mutation{
  upsertTestData(
    create:{
      testId: 3456,
      testNumber:"5588"
      testAmount:123,
      testStatus:"t1"
    }
    update:{
      testId: 3456,
      testNumber:"5588"
      testAmount:321,
      testStatus:"t2"
      testCurrency:9933
    }
    where:{testId: 3456}
  ){id}
}
```
Response:
```
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjdeipvm100a20172c52oz8yv",
      "path": [
        "upsertTestData"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "requestId": "api:api:cjdeipvm100a20172c52oz8yv"
    }
  ]
}
```
looks like what broken order of value of parameters
`SELECT  ? , ? , ? , ? , ? FROM DUAL where not exists (select `id` from `hello-world@dev`.`TestData` where `testId` = ? limit 1);, parameters [123,'5588','cjdeiullv00a701726rgglg58',3456,'t1',3456]`

Docker Logs:
```
{"@timestamp":"2018-02-08T13:11:15.420+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjdeiullo00a50172eesldxpt\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-17","level":"INFO","level_value":20000,"HOSTNAME":"ac55bc54ef4d"}
java.sql.SQLException: (conn=33) Incorrect integer value: 't1' for column 'testAmount' at row 1
at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:184)
at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
at slick.jdbc.Invoker.first(Invoker.scala:31)
at slick.jdbc.Invoker.first$(Invoker.scala:30)
at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
at scala.collection.Iterator.foreach(Iterator.scala:929)
at scala.collection.Iterator.foreach$(Iterator.scala:929)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
at scala.collection.IterableLike.foreach(IterableLike.scala:71)
at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Incorrect integer value: 't1' for column 'testAmount' at row 1
Query is: INSERT INTO `hello-world@dev`.`TestData` ( `testNumber` , `testId` , `testStatus` , `id` , `testAmount` ) SELECT  ? , ? , ? , ? , ? FROM DUAL where not exists (select `id` from `hello-world@dev`.`TestData` where `testId` = ? limit 1);, parameters [123,'5588','cjdeiullv00a701726rgglg58',3456,'t1',3456]
at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
... 24 more
[Bugsnag - local / testing] Error report: com.bugsnag.Report@5195347c
```

**Comment by etx** [comment]
They merged the fix yesterday. Should be in the next release of the docker image I would assume.

**Comment by ivanhodos** [comment]
cool thanks!

**Comment by marktani** [comment]
You can already test it locally by doing

```
npm install -g prisma@beta
prisma local upgrade
```

The `beta` channel points to the latest commit.

Note that when running the `beta` channel, you might encounter unexpected behaviour.
Therefore, make sure to run a local backup using `prisma export` before, to stay on the safe side 🙂
