### ISSUE TITLE
prisma mysql instance issues

### ISSUE THREAD

**Issue by rsatyan** [graphcool/prisma#1805]
# Bug Report

**Current behavior**

WARNING: Exception thrown during asynchronous load
java.sql.SQLSyntaxErrorException: (conn=303) Unknown column 'x2.ownerId' in 'field list'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
        at slick.jdbc.Invoker.foreach(Invoker.scala:48)
        at slick.jdbc.Invoker.foreach$(Invoker.scala:47)
        at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
        at slick.jdbc.Invoker.firstOption(Invoker.scala:24)
        at slick.jdbc.Invoker.firstOption$(Invoker.scala:22)
        at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
        at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:57)
        at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:56)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown column 'x2.ownerId' in 'field list'
Query is: select x2.`id`, x2.`webhookUrl`, x2.`ownerId`, x2.`secrets`, x2.`allowQueries`, x2.`allowMutations`, x2.`functions`, x3.`projectId`, x3.`revision`, x3.`schema`, x3.`functions`, x3.`status`, x3.`applied`, x3.`rolledBack`, x3.`steps`, x3.`errors`, x3.`startedAt`, x3.`finishedAt` from `Project` x2, `Migration` x3 where ((x3.`projectId` = 'tst@dev') and (x2.`id` = 'tst@dev')) and (x3.`status` = 'SUCCESS') order by x3.`revision` desc limit 1
**Reproduction**

> If your problem can be reproduced with a certain service definition, please create a new GitHub repository with the reproduction instructions.

**Expected behavior?**

**Comment by rsatyan** [comment]
This bug can be closed. I found the solution. Needed to upgrade the local docker container.

**Comment by marktani** [comment]
Cheers!
