### ISSUE TITLE
GraphQLNonNull from another module or realm

### ISSUE THREAD

**Issue by maarteNNNN** [graphcool/prisma#1924]
I was programming on my laptop on work. When I arrived home I cloned the code but something is going wrong.

`Cannot use GraphQLNonNull \"User!\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.`

This is the console output
```
Error: Cannot use GraphQLNonNull "User!" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/home/maarten/Programming/February/ine/server/node_modules/graphql/jsutils/instanceOf.js:15:13)
    at isNonNullType (/home/maarten/Programming/February/ine/server/node_modules/graphql/type/definition.js:168:35)
    at isWrappingType (/home/maarten/Programming/February/ine/server/node_modules/graphql/type/definition.js:241:30)
    at Object.getNamedType (/home/maarten/Programming/February/ine/server/node_modules/graphql/type/definition.js:286:12)
    at Object.getTypeForRootFieldName (/home/maarten/Programming/February/ine/server/node_modules/graphql-binding/dist/utils.js:40:22)
    at buildInfoForAllScalars (/home/maarten/Programming/February/ine/server/node_modules/graphql-binding/dist/info.js:17:24)
    at Object.buildInfo (/home/maarten/Programming/February/ine/server/node_modules/graphql-binding/dist/info.js:7:16)
    at Proxy.<anonymous> (/home/maarten/Programming/February/ine/server/node_modules/prisma-binding/dist/src/Handler.js:53:38)
    at signup (/home/maarten/Programming/February/ine/server/src/resolvers/Mutation/auth.js:7:40)
    at <anonymous>
```

On the laptop everything was working fine.

Here on my desktop every mutation at port `4000` is failing.

**Comment by maarteNNNN** [comment]
I had to downgrade prisma to the same version which is `1.1.2`. Any ideas what might've broken while upgrading?

**Comment by thehashrocket** [comment]
I solved this by doing `npm i -g prisma`.
