### ISSUE TITLE
CLI Export fails when logged in on shared cluster

### ISSUE THREAD

**Issue by LawJolla** [graphcool/prisma#1933]
# Bug Report

**Current behavior**

Fails to export `prisma export`

**Reproduction**

`prisma export` fails with `TypeError: Cannot read property 'jsonElements' of undefined`.  Reading the debug (below) the problem seems to be the download url is invalid because the export function isn't taking into account that I'm logged in.

It's trying url `https://us1.prisma.sh/wk_v2_server/dev/export`
The correct url is: `https://us1.prisma.sh/[my-name-space]/wk_v2_server/dev/export

(As an aside, I tried to work out a PR, but #1932 put up too much of a fight.)

**Expected behavior?**

An exported zip file.

```
 DEBUG="*" prisma export -e .env      
  config CWD /Users/dennismacbookpro/PhpstormProjects/wk_v2_server +0ms
  config HOME /Users/dennismacbookpro +6ms
  config definitionDir /Users/dennismacbookpro/PhpstormProjects/wk_v2_server/database +9ms
  config definitionPath /Users/dennismacbookpro/PhpstormProjects/wk_v2_server/database/prisma.yml +0ms
  cli { isGlobal: true } +0ms
  StatusChecker setting status checker +0ms
  cli command id export +16ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/dennismacbookpro/Library/Caches/prisma/plugins.json +0ms
  cli:plugincache Got plugin from cache +2ms
  cli:plugincache /Users/dennismacbookpro/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::1c5b:4e7d:4595:2f8', '10.0.1.33', 'fe80::c482:b6ff:fe26:fb9b', 'fe80::c917:b454:22bb:8bf7', 'fe80::bc90:f472:ed82:a916', 'fe80::604f:8058:dc7b:bf10', 'fe80::c772:7296:4e85:2aed', 'fe80::bd51:93ee:872c:718', 'fde9:809d:3624:a282:bd51:93ee:872c:718', 'fe80::aede:48ff:fe00:1122' ] +0ms
  cli-engine:plugins:manager required +711ms
  plugin required command +715ms
  Environment [ 'prisma-eu1', 'prisma-us1' ] +0ms
  Environment { 'prisma-eu1': 'https://eu1.prisma.sh',
  Environment   'prisma-us1': 'https://us1.prisma.sh' } +0ms
  StatusChecker setting status checker +2s

Downloading nodes...  client Downloading from https://us1.prisma.sh/wk_v2_server/dev/export +0ms
  client {"fileType":"nodes","cursor":{"table":0,"row":0,"field":0,"array":0}} +0ms
  Exporter { code: 3016,
  Exporter   requestId: 'api:api:cjds6f0vtu5vf0190kse4hker',
  Exporter   error: 'Project not found: \'wk_v2_server@dev\'' } +2s
 !
TypeError: Cannot read property 'jsonElements' of undefined
    at Exporter.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/export/Exporter.ts:126:26)
    at step (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/export/Exporter.js:32:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/export/Exporter.js:13:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/export/Exporter.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1

```

**Comment by marktani** [comment]
Are you sure you got the service name/stage right? https://us1.prisma.sh/wk_v2_server/dev says it's not available.

**Comment by LawJolla** [comment]
It’s not available. It should have my “namespace”. I think it’s configured correctly on my end — at least the development spins up correctly and the playground environment points to the name spaced service.

**Comment by marktani** [comment]
Does the cluster property in `prisma.yml` contain the missing namespace?

**Comment by LawJolla** [comment]
On 1.3.0-beta5 everything works!  Closing this one, thanks!
