### ISSUE TITLE
Whoops. Looks like an internal server error.

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#2063]
Thanks to @ellipticaldoor for reporting the following issue.

---

When I do the following command

``` shell
graphql create test --boilerplate node-basic
```
 And I pick local
![image](https://user-images.githubusercontent.com/3449006/36647227-4736eaaa-1a7a-11e8-94df-20135ce0bde5.png)

I get this error
```
Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cje3d0k5f00030140thzrgw97: {"response":{"data":{"addProject":null},"errors":[{"message":"Whoops. Looks like an internal server error. Search your cluster logs for request ID: cluster:cluster:cje3d0k5f00030140thzrgw97","path":["addProject"],"locations":[{"line":2,"column":9}],"requestId":"cluster:cluster:cje3d0k5f00030140thzrgw97"}],"status":200},"request":{"query":"      mutation addProject($name: String! $stage: String! $secrets: [String!]) {\n        addProject(input: {\n          name: $name,\n          stage: $stage\n          secrets: $secrets\n        }) {\n          project {\n            name\n          }\n        }\n      }\n      ","variables":{"name":"test","stage":"dev","secrets":["mysecret123"]}}}
    at GraphQLClient.<anonymous> (/Users/miguel/src/graphql/test/node_modules/graphql-request/src/index.ts:71:13)
    at step (/Users/miguel/src/graphql/test/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/Users/miguel/src/graphql/test/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/Users/miguel/src/graphql/test/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
Exiting with code: 1

SyntaxError: Unexpected number in JSON at position 4
    at JSON.parse (<anonymous>)
    at /Users/miguel/src/graphql/test/.install/node_modules/graphql-boilerplate-install/src/prisma.ts:18:23
    at <anonymous>
✖
TypeError: Cannot read property 'httpEndpoint' of undefined
    at module.exports (/Users/miguel/src/graphql/test/.install/index.js:22:64)
    at <anonymous>
FAIL
```

**Comment by marktani** [comment]
Hey @ellipticaldoor, can you share your `prisma cluster logs`? 🙂

**Comment by ellipticaldoor** [comment]
@marktani looks like is working now :)

**Comment by marktani** [comment]
Great! :slightly_smiling_face:
