### ISSUE TITLE
Error on creating a node with nested connect 

### ISSUE THREAD

**Issue by mwonng** [graphcool/prisma#2108]
Hi there, 

Does anyone meet this problem or am i make a wrong usage for mutation?

I was trying to **create** some orderItem and **connect** orderItem to a product **in creating** a order.

Here is my mutation:

```
mutation {
  createOrder(
   data: {
    currency: {
      connect: {
        id: "cjesl8rq600260902uaj9uv3c"
      }
    }
    customer: {
      connect: {
        id: "cjewdiu2g01bz0902q5mrfkz7"
      }
    }
    note: "test"
    orderItems: {
      create: [
        {
          sku: "TS"
          currentPrice: 299
          quantity: 3
          // this production connect now working 
          product: {
            connect: {
              id: "cjesldmm3002k0902f21dh6op"
            }
          }
        },
      ]
    }
  } 
  ){
    id
    note
    customer {
      firstName
      lastName
    }
    currency {
      shortName
      fullName
    }
    orderItems {
      sku
      currentPrice
      quantity
    }
  }
}
```

without 45 lines below commet, it works well. but if i want to add connection to a product, it shows error.

error on terminal:

```
[GraphQL error]: Message: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjewqmlmy00hm0902m3l2rvfj, Location: [object Object], Path: createOrder
[Network error]: Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjewqmlmy00hm0902m3l2rvfj
Error: Whoops. Looks like an internal server error. Search your cluster logs for request ID: api:api:cjewqmlmy00hm0902m3l2rvfj
    at BatchedGraphQLClient.<anonymous> (/Users/wanghk/code/Meerkat/local_server/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:68:15)
    at step (/Users/wanghk/code/Meerkat/local_server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/wanghk/code/Meerkat/local_server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/wanghk/code/Meerkat/local_server/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

and logs on Local docker:

```
{"@timestamp":"2018-03-18T11:48:32.690+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"api:api:cjewqmlmy00hm0902m3l2rvfj\",\"projectId\":\"graphqlserver@dev\",\"payload\":{\"request_duration\":\"40\",\"throttled_by\":\"0\"}}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-14","level":"INFO","level_value":20000,"HOSTNAME":"d102a08d1490"}
{"@timestamp":"2018-03-18T12:05:00.002+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjewr7rhe00hu0902nfeu71a9\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-14","level":"INFO","level_value":20000,"HOSTNAME":"d102a08d1490"}
{"key":"error/unhandled","requestId":"api:api:cjewr7rhe00hu0902nfeu71a9","clientId":"graphqlserver@dev","payload":{"exception":"java.sql.SQLSyntaxErrorException: (conn=97) Table 'graphqlserver@dev._ProductOnItem' doesn't exist","query":"mutation {\n  createOrder(data: {currency: {connect: {id: \"cjesl8rq600260902uaj9uv3c\"}}, customer: {connect: {id: \"cjewdiu2g01bz0902q5mrfkz7\"}}, note: \"test\", orderItems: {create: [{sku: \"TS\", currentPrice: 299, quantity: 3, product: {connect: {id: \"cjesldmm3002k0902f21dh6op\"}}}]}}) {\n    id\n    note\n    customer {\n      firstName\n      lastName\n    }\n    currency {\n      shortName\n      fullName\n    }\n    orderItems {\n      sku\n      currentPrice\n      quantity\n    }\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)\\n org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)\\n org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\\n slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)\\n slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)\\n slick.jdbc.Invoker.first(Invoker.scala:31)\\n slick.jdbc.Invoker.first$(Invoker.scala:30)\\n slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)\\n slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)\\n slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)\\n slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)\\n slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)\\n slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)\\n slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:571)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"(conn=97) Table 'graphqlserver@dev._ProductOnItem' doesn't exist"}}
java.sql.SQLSyntaxErrorException: (conn=97) Table 'graphqlserver@dev._ProductOnItem' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.first(Invoker.scala:31)
	at slick.jdbc.Invoker.first$(Invoker.scala:30)
	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:571)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Table 'graphqlserver@dev._ProductOnItem' doesn't exist
Query is: insert into `graphqlserver@dev`.`_ProductOnItem` (`id`, `A`, `B`) Select 'cjewr7rid00i10902ebjje621', (SELECT `id` FROM (SELECT * FROM `graphqlserver@dev`.`OrderItem`) IDFROMWHERE WHERE `id` = ?) , `id` FROM `graphqlserver@dev`.`Product` where `id` = ? on duplicate key update `graphqlserver@dev`.`_ProductOnItem`.id = `graphqlserver@dev`.`_ProductOnItem`.id, parameters ['cjewr7ri300hx0902wgg8rsl3','cjesldmm3002k0902f21dh6op']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
	... 43 more
[Bugsnag - local / testing] Error report: com.bugsnag.Report@325be2a6
java.sql.SQLSyntaxErrorException: (conn=97) Table 'graphqlserver@dev._ProductOnItem' doesn't exist
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.first(Invoker.scala:31)
	at slick.jdbc.Invoker.first$(Invoker.scala:30)
	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
	at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:240)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:240)
	at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:238)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:534)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:534)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:571)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Table 'graphqlserver@dev._ProductOnItem' doesn't exist
Query is: insert into `graphqlserver@dev`.`_ProductOnItem` (`id`, `A`, `B`) Select 'cjewr7rid00i10902ebjje621', (SELECT `id` FROM (SELECT * FROM `graphqlserver@dev`.`OrderItem`) IDFROMWHERE WHERE `id` = ?) , `id` FROM `graphqlserver@dev`.`Product` where `id` = ? on duplicate key update `graphqlserver@dev`.`_ProductOnItem`.id = `graphqlserver@dev`.`_ProductOnItem`.id, parameters ['cjewr7ri300hx0902wgg8rsl3','cjesldmm3002k0902f21dh6op']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
	... 43 more
{"@timestamp":"2018-03-18T12:05:00.062+00:00","@version":1,"message":"{\"key\":\"request/complete\",\"requestId\":\"api:api:cjewr7rhe00hu0902nfeu71a9\",\"projectId\":\"graphqlserver@dev\",\"payload\":{\"request_duration\":\"57\",\"throttled_by\":\"0\"}}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-14","level":"INFO","level_value":20000,"HOSTNAME":"d102a08d1490"}
```

**Comment by marktani** [comment]
Hey @mwonng, it seems that your datamodel is not consistent with your database schema.

From the error message, creating a new `_ProductOnItem` table should already do the trick.

Note that you can also run `prisma local nuke` to wipe your internal database and all local data.
This provides a quick way of getting back in a consistent state when in development. We will add better tools to handle such inconsistencies in the future.

**Comment by mwonng** [comment]
thanks @marktani . It seems that's the problem and i reset local docker and deploy again it gonna works. 

Cheers!
