### ISSUE TITLE
graphcool requiring ~/.graphcool file

### ISSUE THREAD

**Issue by helpse** [graphcool/prisma#2128]
# Bug Report

**Current behavior**
When running `graphcool playground` I'm getting

```
vagrant@ubuntu-xenial:~/react-graphql/quickstart-with-apollo/server$ graphcool playground
  config CWD /home/vagrant/react-graphql/quickstart-with-apollo/server +0ms
  config HOME /home/vagrant +1ms
  config definitionDir /home/vagrant/react-graphql/quickstart-with-apollo/server +1ms
  config definitionPath /home/vagrant/react-graphql/quickstart-with-apollo/server/graphcool.yml +0ms
  config homepath /home/vagrant/.graphcoolrc +0ms
  config localRCPath /home/vagrant/react-graphql/quickstart-with-apollo/server/.graphcoolrc +0ms
  config globalRCPath /home/vagrant/.graphcoolrc +0ms
  cli command id playground +0ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /home/vagrant/.cache/graphcool/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /home/vagrant/.cache/graphcool/plugins.json +0ms
  plugins findCommand graphcool-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /usr/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
  cli-engine:plugins:manager required +330ms
  plugin required command +332ms
  EnvironmentMigrator graphcoolPath /home/vagrant/.graphcool does not exist +0ms
Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/lib/node_modules/graphcool/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
Exiting with code: 1
```
Also here:

```
vagrant@ubuntu-xenial:~/react-graphql/quickstart-with-apollo/server$ graphcool --version
  config CWD /home/vagrant/react-graphql/quickstart-with-apollo/server +0ms
  config HOME /home/vagrant +1ms
  config definitionDir /home/vagrant/react-graphql/quickstart-with-apollo/server +0ms
  config definitionPath /home/vagrant/react-graphql/quickstart-with-apollo/server/graphcool.yml +0ms
  config homepath /home/vagrant/.graphcoolrc +1ms
  config localRCPath /home/vagrant/react-graphql/quickstart-with-apollo/server/.graphcoolrc +0ms
  config globalRCPath /home/vagrant/.graphcoolrc +0ms
  cli command id version +0ms
  EnvironmentMigrator graphcoolPath /home/vagrant/.graphcool does not exist +0ms
graphcool-framework/0.11.5 (linux-x64) node-v8.10.0
```

**Reproduction**
run graphcool playground

**Expected behavior?**
Playground shows up

**Comment by marktani** [comment]
Issue moved to [graphcool/graphcool-framework #497](https://github.com/graphcool/graphcool-framework/issues/497) via [**ZenHub**](https://www.zenhub.com/)
