### ISSUE TITLE
Unable to connect Post to User

### ISSUE THREAD

**Issue by harrysolovay** [graphcool/prisma#2135]
# Bug Report

Upon calling the createPost mutation (which tries to connect the post to the author), I get the following error:

`
Error: Cannot return null for non-nullable field Post.author.
    at completeValue (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:638:13)
    at completeValueWithLocatedError (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:585:21)
    at completeValueCatchingError (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:554:12)
    at resolveField (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:500:10)
    at /Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:367:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:364:42)
    at collectAndExecuteSubfields (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:781:10)
    at completeObjectValue (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:771:10)
    at completeValue (/Users/harrysolovay/DEV/Minno/2/server/node_modules/graphql/execution/execute.js:667:12)
` 

Here is the schema.graphql:

`

    type Mutation {
      post(
          type: String!,
          body: String,
          location: String
      ): Post!
    }

    type User {

      id: ID! @unique
      createdAt: DateTime!
      updatedAt: DateTime!

      facebookId: String @unique
      facebookName: String
      facebookFriends: [User!]!

    }

    type Post {

      id: ID! @unique
      createdAt: DateTime!
      updatedAt: DateTime!

      author: User!
    
      type: String!
      body: String

      location: String

    }

`

Here is the post resolver:

`

    const post = async (parent, args, ctx, info) => {

      const userId = getUserId(ctx)

      let data = {
          author : { connect : { id : userId } },
          body : args.body,
          ...(
              args.location
                  ? { location : args.location }
                  : null
          ),
          type : args.type
      }

      const response = await ctx.db.mutation.createPost({ data })

      return response

    }

`

When I log out "data" (which I pass into the mutation), it shows up as expected:

`
  {
    author: {
      connect: {
        id: 'cjf0gryks000j01316pz263m4'
      }
    },
    body: 'testing text uploads',
    location: 'at home',
    type: 'text'
  }
`

Nevertheless I get the error "Cannot return null for non-nullable field Post.author."

Any suggestions?

Thank you in advance for taking the time to help me get up and running. This probably won't be the last time you hear from me haha, so we should get acquainted: I'm Harry. And I love your product.

**Comment by maarteNNNN** [comment]
```javascript
  async createDraft(parent, { title, body, location, type }, ctx, info) {
    const userId = getUserId(ctx)
    return ctx.db.mutation.createPost(
      {
        data: {
          title,
          body,
          location,
          type,
          author: {
            connect: { id: userId },
          },
        },
      },
      info
    )
  },
```

Try it like this

**Comment by harrysolovay** [comment]
My computer crashed :(

fortunately I have everything backed up. As soon as I get my computer fixed, I'll try it that way & get back to you about whether or not it worked. Thank you!

**Comment by harrysolovay** [comment]
It worked!!! Closing the issue :)
