### ISSUE TITLE
Postgres connector can't connect with non-default user

### ISSUE THREAD

**Issue by dpetrick** [graphcool/prisma#2270]
**Issue:** If Prisma tries to connect to a PostgreSQL instance with a user any other than `postgres` (the default user), it fails with a database not found error. This is due to how PostgreSQL handles connection strings - if no database is given, it looks for a database with the 

We currently do not honor the hierarchy PostgreSQL has with databases containing schemas.

**Fix:** Implement correct database and schema handling.

**Comment by Sharlaan** [comment]
Re-opening this, since i can't connect at all if i use another POSTGRES_USER different thanthe default postgres.

prisma/1.12.2 (windows10-x64) node-v10.7.0
postgres latest (10.4)

docker-compose.yml
```yml
version: '3'
services:
  # TODO: Add graphql-container

  prisma:
    # for production image, check https://hub.docker.com/r/prismagraphql/prisma-prod/tags/
    image: prismagraphql/prisma:1.12
    container_name: prisma-container
    restart: always
    ports:
    - ${PRISMA_PORT}:${PRISMA_PORT}
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            port: ${DB_PORT}
            database: ${DB_NAME}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true

  postgres:
    image: postgres
    container_name: database-container
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
```

.env.dev
```
####  DEVELOPEMENT ENVIRONMENT VARIABLES  ####
NODE_ENV=development

# API
API_DEBUG=true
API_HOST=localhost
API_PLAYGROUND=/playground
API_PORT=4000
API_PROTOCOL=http
APP_SECRET=app_secret

# PRISMA LAYER
PRISMA_DEBUG=true
PRISMA_HOST=localhost
PRISMA_PORT=4466
PRISMA_PROTOCOL=http
PRISMA_SECRET=prisma_secret
PRISMA_SERVICE=shop
PRISMA_STAGE=local

# DATABASE
DB_HOST=postgres
DB_NAME=graphql-shop
DB_PORT=5432
DB_USER=prisma
DB_PASSWORD=prisma
```

`docker logs prisma-container`
```
Jul 30, 2018 3:31:49 PM org.postgresql.Driver connect
SEVERE: Connection error:
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:69)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
        ... 15 more

Jul 30, 2018 3:31:50 PM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: ConnectException occurred while connecting to localhost:5432
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:69)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
