### ISSUE TITLE
Local cluster does not start after upgrade to 1.7

### ISSUE THREAD

**Issue by mctep** [graphcool/prisma#2343]
# Bug Report

I has upgraded local cluster from `1.5` to `1.7`.

**Current behavior**

Local cluster does not start after upgrade to 1.7. Removing image does not help.

```
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
prismagraphql/prisma          1.7                 b1190482328f        3 days ago          196MB
prismagraphql/prisma          1.5                 69cd9a69fb4f        4 weeks ago         201MB
```

Container restarts instantly with following errors:

```
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: while scanning a simple key
 in 'string', line 5, column 1:
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A ... 
    ^
could not find expected ':'
 in 'string', line 6, column 1:
    Nfv1ynN9qgbzeawkO9nsDbn+QZLMUg+J ... 
    ^
2018-05-04T12:04:58.608321700Z 
at scala.sys.package$.error(package.scala:27)
at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:38)
at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:38)
at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:15)
at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:12)
at scala.Function0.apply$mcV$sp(Function0.scala:34)
at scala.Function0.apply$mcV$sp$(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:12)
at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
```

Container variables:

```bash
export PORT=4466
export SCHEMA_MANAGER_SECRET=MUCHSECRET
export SCHEMA_MANAGER_ENDPOINT=http://prisma-database:4466/cluster/schema
export SQL_CLIENT_HOST_CLIENT1=prisma-db
export SQL_CLIENT_HOST_READONLY_CLIENT1=prisma-db
export SQL_CLIENT_HOST=prisma-db
export SQL_CLIENT_PORT=3306
export SQL_CLIENT_USER=root
export SQL_CLIENT_PASSWORD=graphcool
export SQL_CLIENT_CONNECTION_LIMIT=10
export SQL_INTERNAL_HOST=prisma-db
export SQL_INTERNAL_PORT=3306
export SQL_INTERNAL_USER=root
export SQL_INTERNAL_PASSWORD=graphcool
export SQL_INTERNAL_DATABASE=graphcool
export CLUSTER_ADDRESS=http://localhost:4466
export SQL_INTERNAL_CONNECTION_LIMIT=10
export CLUSTER_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo7kuxibi28jalaXJ+qNn
Nfv1ynN9qgbzeawkO9nsDbn+QZLMUg+JzaQY6HwIbOV3R92DKyezQrunn/hsACiD
UZsMnNrcV8PiIgcV3rHTkfz2AxqYg6JnBySTiaOAqnPGgxNb74oagNp1kABRvI2A
G3LxyCFMpkpEY/mrztDVT+pbN6eEcYotplTqN2ibH5ia14x6uhN/PkrJUckgtNHL
n3dfNXIw+erPmy+pdbRmlvBDa5IP9n8Vm5o3/zSwbvRMhKoey2FPwMEek2MblJNA
ekQkhpgVRtG+SwDdc08GXDqwlvu1eunsiBWlFThKJtP+H0pcPp9WueoGSNu1UI3n
oQIDAQAB
-----END PUBLIC KEY-----

export BUGSNAG_API_KEY=
export ENABLE_METRICS=0
export JAVA_OPTS=-Xmx1G
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin
export JAVA_VERSION_MAJOR=8
export JAVA_VERSION_MINOR=172
export JAVA_VERSION_BUILD=11
export JAVA_PACKAGE=server-jre
export JAVA_JCE=standard
export JAVA_HOME=/opt/jdk
export GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc
export GLIBC_VERSION=2.27-r0
export LANG=C.UTF-8
export COMMIT_SHA=6a55f0a572acfb013a149968b63e5cfee0b56aba
export CLUSTER_VERSION=1.7.4
```

**Comment by marktani** [comment]
Can you share your `docker-compose.yml`?

**Comment by mctep** [comment]
As far as I understand using of `docker-compose.yml` was introduced in `v1.7`. Before this version I didn't have it. So I have migrated my environment to `docker-compose` in accordance with [Documentation](https://www.prisma.io/docs/reference/prisma-servers-and-dbs/prisma-servers/docker-aira9zama5) and it works well.

So I think this issue should be closed.

**Comment by mctep** [comment]
Related issue #2364
