### ISSUE TITLE
Unexpected token = when using csv-stringify

### ISSUE THREAD

**Issue by Melv** [graphcool/prisma#958]
I am getting a similar error as mentioned in #898, but on another module

**Current behavior**

I used this in a resolver
```
const csvStringify = require('csv-stringify')
```
it did work before , but if I update my function now I get 

```
SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Module._compile (/data/sandbox/lib/module.js:127:21)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at WebtaskModule.require (/data/sandbox/lib/module.js:101:19)
at require (/data/sandbox/lib/module.js:136:21)
at Object.<anonymous> (/data/io/ef95ab20d1eb4198ac16f74f35b9bcc6/webtask.js:7:20)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)
```

**Reproduction**

using @marktani  example I did reduced it to `csv-stringify` module

```graphql
type AdditionPayload {
  sum: Int!
}

extend type Query {
  add(a: Int! b: Int!): AdditionPayload
}
```

```javascript
const csvStringify = require('csv-stringify')

module.exports = function sum(event) {
  return { data: { sum: 12 } }
}
```

**Expected behavior?**
No error

**Comment by marktani** [comment]
This issue has been moved to [graphcool/graphcool-framework](https://github.com/graphcool/graphcool-framework/).
