### ISSUE TITLE
Can't run graphcool local up

### ISSUE THREAD

**Issue by MetaCorp** [graphcool/prisma#970]
I'm getting this error when running graphcool local up on windows 10 after fresh graphcool init (version 0.9.0)

```
Running local Graphcool cluster at http://localhost:60000
Running local FaaS runtime at http://localhost:60050
This may take several minutes
$ docker-compose up -d --remove-orphans

docker   Traceback (most recent call last):
docker     File "docker-compose", line 6, in <module>
docker     File "compose\cli\main.py", line 68, in main
docker     File "compose\cli\main.py", line 121, in perform_command
docker     File "compose\cli\main.py", line 938, in up
docker     File "compose\project.py", line 417, in up
docker     File "compose\project.py", line 646, in warn_for_swarm_mode
docker     File "site-packages\docker\api\daemon.py", line 90, in info
docker     File "site-packages\docker\utils\decorators.py", line 46, in inner
docker     File "site-packages\docker\api\client.py", line 189, in _get
docker     File "site-packages\requests\sessions.py", line 488, in get
docker     File "site-packages\requests\sessions.py", line 475, in request
docker     File "site-packages\requests\sessions.py", line 596, in send
docker     File "site-packages\requests\adapters.py", line 423, in send
docker     File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
docker     File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
docker     File "httplib.py", line 1042, in request
docker     File "httplib.py", line 1082, in _send_request
docker     File "httplib.py", line 1038, in endheaders
docker     File "httplib.py", line 882, in _send_output
docker     File "httplib.py", line 844, in send
docker     File "site-packages\docker\transport\npipeconn.py", line 31, in connect
docker     File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
docker     File "site-packages\docker\transport\npipesocket.py", line 50, in connect
docker   pywintypes.error: (2, 'WaitNamedPipe', 'Le fichier sp\xe9cifi\xe9 est introuvable.')
docker   Failed to execute script docker-compose
 !    4294967295
```

**Comment by kbrandwijk** [comment]
As far as I know, there are still issues with running graphcool local on Windows.

**Comment by lolcoolkat** [comment]
Fixed this issue btw! Make sure you have Docker installed (i'm assuming you're on a Windows computer) from here https://docs.docker.com/docker-for-windows/install/

And also before you try and start docker; be sure to have Hyper-V enabled on your computer as well. Hyper-V can only be enabled on Windows 10 Pro or Enterprise btw, so if you have Windows 10 Home.. you'll need to upgrade to Pro or Enterprise.

**Comment by emipc** [comment]
You must start Docker before running this command.

**Comment by marktani** [comment]
Closing this for now, if you still encounter a problem, please create a new issue.
